let data2 ={
	"name":"map",
	"children":[
		{
			"name":"ecosystem1",
			"children":[
				{
					"name":"group1",
					"children":[
						{"name":"tool1","value":1},
						{"name":"tool2","value":1},
						{"name":"tool3","value":1}

					]
				},
				{
					"name":"group2",
					"children":[
						{"name":"tool4","value":1},
						{"name":"tool5","value":1},
						{"name":"tool6","value":1}

					]
				},
				{
					"name":"tool7",
					"value":1
				}
			]
		},
		{
			"name":"ecosystem2",
			"children":[
				{
					"name":"group3",
					"children":[
						{"name":"tool8","value":1},
						{"name":"tool9","value":1},
						{"name":"tool10","value":1},
						{"name":"tool11","value":1}

					]
				},
				{
					"name":"group4",
					"children":[
						{"name":"tool12","value":1},
						{"name":"tool13","value":1},
						{"name":"tool14","value":1},
						{"name":"tool15","value":1},
						{"name":"tool16","value":1},
						{"name":"tool17","value":1},
						{"name":"tool18","value":1},
						{"name":"tool19","value":1},
						{"name":"tool20","value":1},
						{"name":"tool21","value":1}
					]
				},
				{
					"name":"group5",
					"children":[
						{"name":"tool22","value":1},
						{"name":"tool23","value":1},
						{"name":"tool24","value":1},
						{"name":"tool25","value":1},
						{"name":"tool26","value":1},
						{"name":"tool27","value":1},
						{"name":"tool28","value":1},
						{"name":"tool29","value":1},
						{"name":"tool30","value":1},
						{"name":"tool31","value":1}
					]
				}
			]
		},
		{
			"name":"ecosystem3",
			"children":[
				{
					"name":"group6",
					"children":[
						{"name":"tool32","value":1},
						{"name":"tool33","value":1},
						{"name":"tool34","value":1},
						{"name":"tool35","value":1}

					]
				},
				{
					"name":"group7",
					"children":[
						{"name":"tool36","value":1},
						{"name":"tool37","value":1},
						{"name":"tool38","value":1},
						{"name":"tool39","value":1},
						{"name":"tool40","value":1},
						{"name":"tool41","value":1},
						{"name":"tool42","value":1},
						{"name":"tool43","value":1},
						{"name":"tool44","value":1},
						{"name":"tool45","value":1}
					]
				},
				{
					"name":"group8",
					"children":[
						{"name":"tool46","value":1},
						{"name":"tool47","value":1},
						{"name":"tool48","value":1},
						{"name":"tool49","value":1},
						{"name":"tool50","value":1},
						{"name":"tool51","value":1},
						{"name":"tool52","value":1},
						{"name":"tool53","value":1},
						{"name":"tool54","value":1},
						{"name":"tool55","value":1}
					]
				}
			]
		}
	]
}